spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    maxActive: 50
    maxIdle: 10
    maxWait: 10000
    minIdle: 5
mybatis:
  type-handlers-package: com.example.mybatisdemo.handler
  mapperLocations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true